spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #        driver-class-name: org.h2.Driver
    # url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/wx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/wx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:myspace2022}

springfox:
  documentation:
    swagger-ui:
      enabled: true